spring:
  application:
    name: doc-ai
  server:
    port: 8080
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
langchain4j:
  zhipu-ai:
    api-key: 
    chat-model:
      model-name: glm-4.5-air
    embedding-model:
        model-name: embedding-2
